export const bikeFields = [
  { name: "name", label: "Bike Name", placeholder: "Bike Name" },
  // {
  //   name: "image",
  //   label: "Images URL",
  //   placeholder: "Images url (comma-separated)",
  // },
  {
    name: "description",
    label: "Bike Description",
    placeholder: "Description",
  },
  {
    name: "isAvailable",
    label: "Is Available",
    placeholder: "Is Available (true/false)",
    type: "boolean",
  },
  {
    name: "pricePerHour",
    label: "Price Per Hour",
    placeholder: "Price Per Hour",
    type: "number",
  },
  { name: "cc", label: "Engine CC", placeholder: "Engine CC", type: "number" },
  { name: "mileage", label: "Mileage", placeholder: "Mileage", type: "number" },
  {
    name: "topSpeed",
    label: "Top Speed",
    placeholder: "Top Speed",
    type: "number",
  },
  { name: "power", label: "Power", placeholder: "Power", type: "number" },
  { name: "tyreType", label: "Tyre Type", placeholder: "Tyre Type" },
  {
    name: "year",
    label: "Manufacturing Year",
    placeholder: "Manufacturing Year",
    type: "number",
  },
  { name: "model", label: "Bike Model", placeholder: "Bike Model" },
  { name: "brand", label: "Bike Brand", placeholder: "Bike Brand" },
  { name: "madeIn", label: "Made In", placeholder: "Made In" },
  { name: "engineType", label: "Engine Type", placeholder: "Engine Type" },
  { name: "fuelSupply", label: "Fuel Supply", placeholder: "Fuel Supply" },
  {
    name: "engineCooling",
    label: "Engine Cooling",
    placeholder: "Engine Cooling",
  },
  {
    name: "noOfCylinders",
    label: "Number of Cylinders",
    placeholder: "Number of Cylinders",
    type: "number",
  },
  {
    name: "startingMethod",
    label: "Starting Method",
    placeholder: "Starting Method",
  },
  {
    name: "fuelTankCapacity",
    label: "Fuel Tank Capacity",
    placeholder: "Fuel Tank Capacity",
    type: "number",
  },
  { name: "brakeType", label: "Brake Type", placeholder: "Brake Type" },
  { name: "abs", label: "ABS", placeholder: "ABS" },
  { name: "batteryType", label: "Battery Type", placeholder: "Battery Type" },
  {
    name: "batteryVoltage",
    label: "Battery Voltage",
    placeholder: "Battery Voltage",
  },
  { name: "headLamp", label: "Head Lamp", placeholder: "Head Lamp" },
  { name: "indicator", label: "Indicator Type", placeholder: "Indicator Type" },
];
